version: '3'
services:
  my-app:
    build: . 
    ports: 
    - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports: 
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
     - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local