version: '3.0'
services:
  my-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
    - 3000:3000

  mongo:
    image: mongo
    ports:
     - 27018:27018
    volumes:
     - mongo-data:/data/db
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports: 
     - 8081:8081
    volumes: 
     - mongo-data:/data/db      
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
     - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@localhost:27018/
     - ME_CONFIG_MONGODB_SERVER=localhost

volumes:
  mongo-data:
    driver: local

networks:
  mongo-compose-network:
    driver: bridge